spring:
  application:
    name: batch.kafka

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    properties:
      security.protocol: SSL
      ssl.truststore.location: /tmp/kafka-certs/truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.keystore.location: /tmp/kafka-certs/keystore.p12
      ssl.keystore.password: ${KAFKA_KEYSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.key.password: ${KAFKA_KEYSTORE_PASSWORD}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      enable-idempotence: true
      transactional-id: payment-tx-
      batch-size: 32768
      linger-ms: 10

    consumer:
      group-id: payment-service
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        isolation.level: read_committed
        spring.json.trusted.packages: "*"

    listener:
      type: batch
      ack-mode: manual

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    com.spring.batch.kafka: DEBUG
